### PR TITLE
Adds Westwood Sans Font

### PR DESCRIPTION
**Pull request by doubleiis02**
- added additional npm install guidelines to readme
- added Westwood Sans download & install instructions to readme
- changed font family from Poppins to Westwood Sans
- set body's margin to 0 in order to get app to fill the entire page width

### CODE REVIEW

**Comment by reginawang99** [comment]
@matthewcn56 can u also consider whether Westwood fonts is too much? i remember some ppl having issues downloading when doing the figma and them quitting

i wonder if theres a way to help download it onto this repo already?

**Comment by doubleiis02** [comment]
I added version 1.0 of Westwood Sans inside assets and updated readme instructions. The file is 40 KB, that's not too big right? @matthewcn56 what are your thoughts

**Comment by reginawang99** [comment]
is there a way to prebuild the font or anything so they dont have to double click it? since it works in prod? (i dont really know how fonts work)

**Comment by matthewcn56** [comment]
> @matthewcn56 can u also consider whether Westwood fonts is too much?

Hmm, I think that if we're already centralizing the Learning Labs with the Footer that enforcing the usage of Westwood Sans would make them more cohesive as well.

Playing devil's advocate though, do you guys think that enforcing the usage of a font is too much? Personally I'd be fine with it, and if we're going to be using them for curriculum with our classes or our collars then I think centralizing the usage of a font makes all our LL's look more cohesive.

In terms of using the fonts, I think using web-pack would work if we use the `.ttf` file right? @reginawang99

**Comment by reginawang99** [comment]
im down to setup the font--i just want there to be as little setup as possible for the devs 

- can u test if it works lol im working today - first day lots meeting -  so will not be very throrough @matthewcn56

**Comment by doubleiis02** [comment]
@matthewcn56 [](https://dev.to/atapas/3-quick-ways-to-add-fonts-to-your-react-app-no6) the third way to add fonts on this link here seems to be what we want. I'll try to implement this and let u know

**Comment by matthewcn56** [comment]
> * can u test if it works lol im working today - first day lots meeting -  so will not be very throrough @matthewcn56

Ye, I'll add it into our web pack config later, maybe we can ask design if they want to make Westwood Sans into an NPM package as well 🤔

**Comment by reginawang99** [comment]
yea can we pls make it an npm package haha

**Comment by reginawang99** [comment]
idk if its worth the extra hump of having to setup something else -- if we have to double click, can we maybe wait for it to be an npm package or something and then make a pr into the existing LLs (Python/ML)?

**Comment by matthewcn56** [comment]
> @matthewcn56 the third way to add fonts on [this link](https://dev.to/atapas/3-quick-ways-to-add-fonts-to-your-react-app-no6) seems to be what we want. I'll try to implement this and let u know

Sounds good! @doubleiis02  If our webpack assets yell at you when you try committing or building after adding in the local font with `.ttf`, then you might have to add in `.ttf` to our webpack config for asset handling on line 22 of `webpack.dev.js` and `webpack.prod.js` (instructions for adding in more asset file types within the regex expression is inside the readme)

**Comment by matthewcn56** [comment]
> idk if its worth the extra hump of having to setup something else -- if we have to double click, can we maybe wait for it to be an npm package or something and then make a pr into the existing LLs (Python/ML)?
> 
> thoughts?

Since the `.ttf` package is available to us, if we just add the @font-face in with the path to our ttf file I think we should be fine and they don't have to set anything up?

**Comment by reginawang99** [comment]
ok! ill take a look after u done

**Comment by doubleiis02** [comment]
I added the font face, added `ttf` to the webpack, and updated readme! The font still works after I disable the font on my computer, so I think we are good to go?

**Comment by matthewcn56** [comment]
> yea can we pls make it an npm package haha

kk will ask crystal from ACM Design if she wants to add Westwood Sans to [Fontsource](https://github.com/fontsource/fontsource) so we can just install it as an yarn/npm package so that future peeps don't have to download the ttf file

**Comment by reginawang99** [comment]
kk ill take a look in like 10!

**Comment by reginawang99** [comment]
looks good to me!! can we possibly make the footer look a little better tho lol (like not bolded or something)

**Comment by matthewcn56** [comment]
@reginawang99 can you add your review? Comments don't allow merging in

**Comment by doubleiis02** [comment]
*adjust footer oops

**Comment by doubleiis02** [comment]
> @reginawang99 can you add your review? Comments don't allow merging in

she's in a meeting rn, also what do you mean about the comments?
also take a look at the footer and lmk if you want any more changes @matthewcn56

**Comment by matthewcn56** [comment]
> also take a look at the footer and lmk if you want any more changes @matthewcn56

Looks good to me too, nice work! Regina can approve the changes and merge it in when she has time.

**Review by reginawang99 — APPROVED** [review]
looks great to me!! is v cool ty jiin :))

really tiny nit: can we possibly name the pr to be something like "add WestwoodSans font"? just to be a lil more descriptve meybe?

**Pull request merged**
